### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by IceTeddy** [xinlc/react-native-baidu-location#3]
iOS版本可以编译成功，debug运行也可以，但是XCode打包的时候会报这个错：
no such file or directory: '/Users/abc/Library/Developer/Xcode/DerivedData/LDL-bfvykyksdsjfpefpdpqfobvltoet/Build/Intermediates.noindex/ArchiveIntermediates/LDL/BuildProductsPath/Release-iphoneos/RNBaiduLocation.framework/RNBaiduLocation'

请问这个要怎么解决啊？

**Comment by xinlc** [comment]
@IceTeddy 没有配置 Framework Search Path ？

**Comment by IceTeddy** [comment]
@xinlc 确认是添加了的
<img width="1452" alt="111" src="https://user-images.githubusercontent.com/1934749/51721899-8e847100-208e-11e9-9a35-ef66e3586f02.png">

**Comment by IceTeddy** [comment]
@xinlc 现在XCode里面所有第三方库全部报错了。。。 
![1548388105706](https://user-images.githubusercontent.com/1934749/51724203-356d0b00-2097-11e9-9534-246225e61972.jpg)

**Comment by xinlc** [comment]
@IceTeddy 请参考Example中Search Paths配置部分
